ddspipe_core/include/ddspipe_core/types/dds/DomainId.hpp
ddspipe_core/src/cpp/types/dds/DomainId.cpp

DomainId had a ctor with a boolean and anything else. Thus, trying to create it from an int (what makes much sense) does not give the expected domain because it is parsed as bool

Fix DomainId ctor common mistake

---

ddspipe_participants/include/ddspipe_participants/reader/rtps/CommonReader.hpp
ddspipe_participants/include/ddspipe_participants/writer/rtps/CommonWriter.hpp
ddspipe_participants/src/cpp/reader/rtps/CommonReader.cpp
ddspipe_participants/src/cpp/writer/rtps/CommonWriter.cpp

After:
- https://github.com/eProsima/Fast-DDS-spy/pull/40

Add more debugging listener callbacks

---

ddspipe_core/src/cpp/types/dynamic_types/schema.cpp
ddspipe_core/test/unittest/types/dynamic_types/resources/char_sequence.msg

This PR fixes the conversion of certain Fast-DDS types (idl) into ROS 2 schema ones.

Fix schema types conversion

---

ddspipe_participants/src/cpp/reader/rtps/CommonReader.cpp
ddspipe_participants/src/cpp/types/dds/TopicDataType.cpp

Communication between DDS Participants (i.e. participants configured through XML) on keyed topics was faulty because the instanceHandle data was not being saved correctly.
Additionally, instanceHandle propagation from a RTPS participant to a DDS one was not being done, as the RTPS reader was not requesting it to remote writers in the first place.

Save instanceHandle data for keyed topics [19601]

---

ddspipe_participants/src/cpp/reader/dds/CommonReader.cpp
ddspipe_participants/src/cpp/writer/dds/CommonWriter.cpp

An assert was going off when the max-depth was set to 0 and both participants used XML.

Fix 0 history depth in XML Participants

---

ddspipe_core/include/ddspipe_core/communication/dds/DdsBridge.hpp
ddspipe_core/include/ddspipe_core/communication/dds/Track.hpp
ddspipe_core/include/ddspipe_core/configuration/DdsPipeConfiguration.hpp
ddspipe_core/include/ddspipe_core/configuration/RoutesConfiguration.hpp
ddspipe_core/include/ddspipe_core/configuration/TopicRoutesConfiguration.hpp
ddspipe_core/include/ddspipe_core/core/DdsPipe.hpp
ddspipe_core/include/ddspipe_core/dynamic/DiscoveryDatabase.hpp
ddspipe_core/include/ddspipe_core/dynamic/ParticipantsDatabase.hpp
ddspipe_core/include/ddspipe_core/interface/ITopic.hpp
ddspipe_core/include/ddspipe_core/types/dds/Endpoint.hpp
ddspipe_core/include/ddspipe_core/types/dds/TopicQoS.hpp
ddspipe_core/include/ddspipe_core/types/participant/ParticipantId.hpp
ddspipe_core/include/ddspipe_core/types/topic/Topic.hpp
ddspipe_core/src/cpp/communication/dds/DdsBridge.cpp
ddspipe_core/src/cpp/communication/dds/Track.cpp
ddspipe_core/src/cpp/configuration/DdsPipeConfiguration.cpp
ddspipe_core/src/cpp/configuration/RoutesConfiguration.cpp
ddspipe_core/src/cpp/configuration/TopicRoutesConfiguration.cpp
ddspipe_core/src/cpp/core/DdsPipe.cpp
ddspipe_core/src/cpp/dynamic/DiscoveryDatabase.cpp
ddspipe_core/src/cpp/dynamic/ParticipantsDatabase.cpp
ddspipe_core/src/cpp/testing/random_values.cpp
ddspipe_core/src/cpp/types/topic/Topic.cpp
ddspipe_participants/src/cpp/utils/utils.cpp
ddspipe_yaml/include/ddspipe_yaml/yaml_configuration_tags.hpp
ddspipe_yaml/src/cpp/YamlReader_types.cpp

In the previous version, the DdsBridge created a reader and a writer for every participant. Then, for each reader, the DdsBridge created a track towards every writer (except the participant's writer unless the participant was configured as a repeater).
In this version, the DdsBridge creates the readers and the writers dynamically. 
- Whenever a participant discovers an external subscriber, the DdsBridge:
1. Creates a writer in the participant who discovered the subscriber.
2. Creates readers in the participants who have a route towards the participant who discovered the subscriber.
- Whenever an external subscriber drops or disconnects, the DdsBridge:
1. Removes its associated writer from every track it was on.
2. Removes the tracks that don't have any writers in them.
**Merge after** 
- …

Only create readers, writers, and tracks when they are going to be used [19421]

---

ddspipe_participants/include/ddspipe_participants/writer/rtps/CommonWriter.hpp
ddspipe_participants/src/cpp/participant/dds/CommonParticipant.cpp
ddspipe_participants/src/cpp/participant/rtps/CommonParticipant.cpp
ddspipe_participants/src/cpp/writer/rtps/CommonWriter.cpp

In the previous version, the changes on reliable-volatile topics were never removed from the RTPS writers' histories. This lead to the congestion of RTPS writers' histories and, at times, to memory exhaustion issues. In this version, RTPS writers free changes (on reliable-volatile topics) once they have been acknowledged by all readers.
In the following example, we launch a DDS Router with two RTPS participants, and publish a hundred 1MB messages on a reliable-volatile topic. Here's the heap memory consumption of the DDS Router before and after this update.
Before (Peak Heap Memory 99.5 MiB):
After (Peak Heap Memory 5.9 MiB):
This version also includes a **bugfix**. In the previous version, RTPS CommonWriters would free space in their full-histories after adding a change. This meant that …

Free the changes that have been acknowledged by all readers (on volatile topics) [19800]

---

ddspipe_core/src/cpp/testing/random_values.cpp
ddspipe_participants/src/cpp/participant/rtps/CommonParticipant.cpp

PR https://github.com/eProsima/DDS-Pipe/pull/57 added to `Topic` class a participant discoverer attribute, but missed to copy this attribute to endpoints simulated via CommonParticipant::simulate_endpoint method, which may cause inconsistencies in some corner cases.

Set discoverer participant in simulated endpoint's topic

---

ddspipe_core/include/ddspipe_core/configuration/DdsPipeConfiguration.hpp
ddspipe_core/include/ddspipe_core/core/DdsPipe.hpp
ddspipe_core/src/cpp/configuration/DdsPipeConfiguration.cpp
ddspipe_core/src/cpp/core/DdsPipe.cpp
ddspipe_participants/src/cpp/participant/dynamic_types/SchemaParticipant.cpp
ddspipe_yaml/include/ddspipe_yaml/yaml_configuration_tags.hpp

In the previous version, the DDS Pipe's callbacks were only triggered by the discovery of readers. In this version, the entity type that triggers the callbacks is configurable. They can be triggered by readers (by default), writers, both readers and writers, and neither readers nor writers.
Merge after:
- https://github.com/eProsima/DDS-Pipe/pull/57
- https://github.com/eProsima/DDS-Pipe/pull/64

Make the trigger of the DDS Pipe callbacks configurable

---

ddspipe_core/src/cpp/communication/dds/DdsBridge.cpp
ddspipe_core/src/cpp/core/DdsPipe.cpp

In the previous version, built-in topics were incompatible with `remove-unused-entities`. Now, `remove-unused-entities` only applies to topics that are discovered (i.e. topics that aren't built-in).
The documentation for this PR can be found at https://github.com/eProsima/DDS-Router/pull/413

Make remove-unused-entities compatible with built-in topics

---

ddspipe_core/src/cpp/communication/dds/Track.cpp
ddspipe_core/src/cpp/types/data/RtpsPayloadData.cpp
ddspipe_participants/include/ddspipe_participants/participant/dds/XmlParticipant.hpp
ddspipe_participants/src/cpp/participant/dds/XmlParticipant.cpp
ddspipe_participants/src/cpp/reader/dds/CommonReader.cpp

After sharing a PayloadPool between DDS and RTPS participants with https://github.com/eProsima/DDS-Pipe/pull/70, payloads would occasionally be released more often than reserved. It only happened on volatile topics when there was a DDS participant. It's unclear what the problem was exactly, but it had to do with the DDS CommonReader taking and ignoring the payloads from its own participant. The fix has been to force XML participants to ignore_local_endpoints. The fix has improved the DDS Router's latency considerably, but it's hard to know exactly by how much without proper latency tests.

Enforce ignore_local_endpoints on XML participants [20182]

---

ddspipe_core/include/ddspipe_core/configuration/CommandlineArgs.hpp

This PR corrects the Warnings thrown in DDSPipe products due to their derived classes of CommandlineArgs.

Add Dll dependency to CommandlineArgs class

---

ddspipe_participants/include/ddspipe_participants/reader/dds/CommonReader.hpp
ddspipe_participants/include/ddspipe_participants/reader/rtps/CommonReader.hpp
ddspipe_participants/src/cpp/reader/dds/CommonReader.cpp
ddspipe_participants/src/cpp/reader/rtps/CommonReader.cpp

**New warnings** reported:
1. **Topic with type mismatch:** [DDSRECORDER_MCAP_HANDLER Warning] TOPIC_MISMATCH_TYPE | Reader found a remote Writer with same topic name but incompatible type
2. **Topic with QoS mismatch:** [DDSRECORDER_MCAP_HANDLER Warning] TOPIC_MISMATCH_QOS | Reader found a remote Writer with incompatible QoS
3. **Missing samples:** [DDSRECORDER_MCAP_HANDLER Warning] SAMPLE_LOST | On readers a data sample was lost and will not be received

[19983] Report more warnings in the readers

---

ddspipe_participants/src/cpp/participant/rtps/DiscoveryServerParticipant.cpp

After PR #93, Router's TCP Discovery Server was failing.
FastDDS currently does not support discovery server's server to have a metatraffic locator with null logical port.
With this PR, logical port will get physical port value. This is only applied to DiscoveryServerParticipant.

TCP discovery server

---

ddspipe_participants/include/ddspipe_participants/participant/auxiliar/EchoParticipant.hpp
ddspipe_participants/include/ddspipe_participants/participant/dds/CommonParticipant.hpp
ddspipe_participants/src/cpp/participant/auxiliar/EchoParticipant.cpp
ddspipe_participants/src/cpp/participant/dds/CommonParticipant.cpp
ddspipe_participants/src/cpp/participant/rtps/CommonParticipant.cpp

Echo participant only advised participant discovery.
With this PR it also advises participant undiscovery when participant has been updated and it is not active.
In addition, participant discovery callback is now also implemented in DdsCommonParticipant, and already implemented discovery callbacks (both for RTPS and DDS) updated to adapt to changes introduced in Fast-DDS middleware (e.g. ignore participant/endpoint feature).

Echo participant undiscovery + Discovery callbacks update

---

ddspipe_core/src/cpp/core/DdsPipe.cpp

This small PR pretends to avoid the following situation: when the rate of reception for a topic is greater than the rate these messages can be processed in the ThreadPool's working threads, a DDS-Pipe instance might get stuck in its destructor. The reason for this is that before disabling internal entities (which would prevent receiving new samples, and abort ongoing tracks' transmission tasks), the thread pool is disabled. Disabling the thread pool makes it wait until all threads are joined (which occurs when all ongoing tasks are completed), but this may never happen in the described scenario.
NOTE: this problem would not happen if applications using DDS-Pipe would always call `DdsPipe::disable` before destroying the object. However DDS-Pipe should be as resilient as possible to the way …

Avoid potential neverending closure

---

ddspipe_participants/include/ddspipe_participants/efficiency/cache_change/CacheChangePool.hpp
ddspipe_participants/src/cpp/efficiency/cache_change/CacheChangePool.cpp

This feature resets changes from the RTPS CacheChangePool before returning them to the pool, fixing the issue discovered in https://github.com/eProsima/DDS-Router/discussions/353.

[21048] Reset cache changes to avoid data fragmentation issues

---

ddspipe_participants/include/ddspipe_participants/reader/rtps/CommonReader.hpp
ddspipe_participants/include/ddspipe_participants/writer/rtps/CommonWriter.hpp
ddspipe_participants/src/cpp/reader/rtps/CommonReader.cpp
ddspipe_participants/src/cpp/writer/rtps/CommonWriter.cpp

In the previous version, `PolicyMasks` were being printed as bitsets, making them unreadable to humans. In this version, they use dev-utils methods to convert them to strings and make them readable.
Merge after:
- https://github.com/eProsima/dev-utils/pull/118

[21227] Print PolicyMasks as strings

---

ddspipe_participants/include/ddspipe_participants/configuration/SimpleParticipantConfiguration.hpp
ddspipe_participants/include/ddspipe_participants/participant/rtps/CommonParticipant.hpp
ddspipe_participants/include/ddspipe_participants/types/address/Address.hpp
ddspipe_participants/src/cpp/configuration/SimpleParticipantConfiguration.cpp
ddspipe_participants/src/cpp/participant/rtps/CommonParticipant.cpp
ddspipe_yaml/src/cpp/YamlReader_participants.cpp

This PR removes the constraint of whitelist elements to be IPv4 addresses, accepting now IPv6 ones as well (for WAN and DiscoverServer participants only) and device names.

Accept v6 interfaces and interface names in whitelist [21531]

---

ddspipe_core/include/ddspipe_core/types/dds/GuidPrefix.hpp
ddspipe_core/src/cpp/types/dds/GuidPrefix.cpp
ddspipe_participants/src/cpp/configuration/DiscoveryServerParticipantConfiguration.cpp
ddspipe_participants/src/cpp/participant/dds/CommonParticipant.cpp
ddspipe_participants/src/cpp/participant/rtps/CommonParticipant.cpp
ddspipe_yaml/include/ddspipe_yaml/YamlReader.hpp
ddspipe_yaml/include/ddspipe_yaml/yaml_configuration_tags.hpp
ddspipe_yaml/src/cpp/YamlReader_participants.cpp
ddspipe_yaml/src/cpp/YamlReader_types.cpp

This PR:
- Makes DiscoveryServer servers' guid prefix optional, as starting from Fast-DDS v3.0.0 release it is no longer required. Nonetheless, it's kept as an optional to allow for communication with clients using previous Fast-DDS versions (these clients need to point to a GUID, so it's necessary to fix one in the server side). Note that not setting a GUID solves a corner case when TCP localhost addresses are used: this is because Fast-DDS performs the transformation of (suitable) locators to localhost based on their associated GUID, which needs to convey certain rules. And so this mechanism only succeeds when the GUID is internally assigned by Fast-DDS instead of manually set by users. 
- Raises YAML reader version (given the previous change, and that `discovery-server-guid` is no …

Make DiscoveryServer servers' guid prefix optional

---

ddspipe_yaml/include/ddspipe_yaml/YamlWriter.hpp
ddspipe_yaml/include/ddspipe_yaml/impl/YamlWriter.ipp
ddspipe_yaml/test/unittest/yaml_writer/YamlWriterTest.cpp
ddspipe_yaml/test/unittest/yaml_writer/YamlWriter_collections_test.cpp

This PR adds support for two YAML serialization formats (compact and extended) and includes the following key changes:
- Addition of new templated function `set(Yaml& yml, const T& value, const bool is_compact)` is added to support writing values into YAML in either compact or extended format, based on the is_compact flag.
- The functionality has also been applied to `set_collection`, allowing collections vectors to be serialized in both compact and extended formats.
- Renaming of set with `TagType`: The function `set(Yaml& yml, const TagType& tag, const T& value)` has been renamed to `set_in_tag(Yaml& yml, const TagType& tag, const T& value)`.

[21812 ] Add templated function to YamlWriter for supporting compact format

---

ddspipe_participants/include/ddspipe_participants/reader/auxiliar/InternalReader.hpp
ddspipe_participants/include/ddspipe_participants/writer/auxiliar/InternalWriter.hpp
ddspipe_participants/src/cpp/writer/auxiliar/InternalWriter.cpp

Move already existing helper class from Fast-DDS-spy repo so that it can be reused in other tools.

Add auxiliar InternalWriter

---

ddspipe_core/src/cpp/communication/rpc/RpcBridge.cpp

found this bug during https://github.com/eProsima/DDS-Pipe/pull/141/.

Check data is taken in RpcBridge::transmit_

---

ddspipe_participants/include/ddspipe_participants/configuration/SimpleParticipantConfiguration.hpp
ddspipe_participants/include/ddspipe_participants/participant/rtps/CommonParticipant.hpp
ddspipe_participants/include/ddspipe_participants/utils/utils.hpp
ddspipe_participants/src/cpp/configuration/SimpleParticipantConfiguration.cpp
ddspipe_participants/src/cpp/participant/dds/CommonParticipant.cpp
ddspipe_participants/src/cpp/participant/rtps/CommonParticipant.cpp
ddspipe_participants/src/cpp/participant/rtps/SimpleParticipant.cpp
ddspipe_participants/src/cpp/utils/utils.cpp
ddspipe_participants/test/unittest/CMakeLists.txt
ddspipe_participants/test/unittest/participant/CMakeLists.txt
ddspipe_participants/test/unittest/participant/rtps/CMakeLists.txt
ddspipe_participants/test/unittest/participant/rtps/SimpleParticipantTests.cpp
ddspipe_yaml/include/ddspipe_yaml/testing/generate_yaml.hpp
ddspipe_yaml/include/ddspipe_yaml/yaml_configuration_tags.hpp
ddspipe_yaml/src/cpp/YamlReader_participants.cpp
ddspipe_yaml/test/unittest/entities/address/YamlGetEntityAddressTest.cpp
ddspipe_yaml/test/unittest/entities/address/test_units/YamlGetEntityAddressTest_get_easy_mode_ip.ipp

This PR adds support for configuring easy mode in SimpleParticipants through the YAML configuration file using a new `ros2-easy-mode` tag.
The option is incompatible with the transports configuration, so easy mode is only configured if it is set as default (`builtin`).
Merge after:
- https://github.com/eProsima/Fast-DDS/pull/5689

Support ROS 2 Easy mode

---

ddspipe_core/src/cpp/types/topic/rpc/RpcTopic.cpp

This PR removes the type information from RPC topics. Currently the creation of an RPC topic is triggered when an entity corresponding to the request or reply topics is discovered. This way, the topic and type names of the other topic conforming the pair is deduced. However it is not possible to deduce the type information, so we leave this field empty until the creation mechanism is adapted to cover this scenario.

Remove type information from RPC topics

---

ddspipe_participants/include/ddspipe_participants/participant/dds/CommonParticipant.hpp
ddspipe_participants/include/ddspipe_participants/participant/dynamic_types/DynTypesParticipant.hpp
ddspipe_participants/include/ddspipe_participants/participant/rtps/CommonParticipant.hpp
ddspipe_participants/src/cpp/participant/dds/CommonParticipant.cpp
ddspipe_participants/src/cpp/participant/dynamic_types/DynTypesParticipant.cpp
ddspipe_participants/src/cpp/participant/rtps/CommonParticipant.cpp
ddspipe_participants/src/cpp/reader/auxiliar/BaseReader.cpp
ddspipe_participants/src/cpp/reader/dds/CommonReader.cpp
ddspipe_participants/src/cpp/reader/rtps/CommonReader.cpp

This PR is a follow up of https://github.com/eProsima/DDS-Router/pull/509 to fix tsan tests of the DDS Router. It fixes two data races:
- First, it uses the `enabled_` atomic boolean of the `BaseReader` to ensure that the `on_data_available_lambda_` is only called when the class has been properly enabled, that is, when the lambda has already been set. This change is not mandatory, but TSAN stops reporting a false positive related to a data race with the the mentioned lambda . 
- Then, it uses DDS/Rtps Listeners as attributes rather than inheriting from them. In this way, a data race between the `on_participant_discovery` callback and the destructor is avoided (data race on vptr (ctor/dtor vs virtual call)). This data rece occurs when a thread makes a call to a virtual method (`"dds.udp"` …

[21670] Fix Data Races on DDS-Pipe

---

ddspipe_participants/include/ddspipe_participants/participant/dynamic_types/DynTypesParticipant.hpp
ddspipe_participants/src/cpp/participant/dynamic_types/DynTypesParticipant.cpp

This PR splits the Listener of DynTypesParticipant into two separated listeners: RTPS and DDS.
In this way, the logic of each listener is isolated from the other. 
Also, it allows the SpyDdsParticipant to store in the DDS listener the GUID of the RTPS listener as it will already be created during the DDS participant construction. This allows to properly filter out any discovery message received from the RTPS listener. 
This PR is necessary to implement:
- https://github.com/eProsima/Fast-DDS-spy/pull/125

Split RTPS and DDS Listeners in DynTypesParticipant

---

ddspipe_participants/include/ddspipe_participants/writer/dds/CommonWriter.hpp
ddspipe_participants/include/ddspipe_participants/writer/dds/MultiWriter.hpp
ddspipe_participants/include/ddspipe_participants/writer/dds/QoSSpecificWriter.hpp
ddspipe_participants/include/ddspipe_participants/writer/dds/SimpleWriter.hpp
ddspipe_participants/include/ddspipe_participants/writer/dds/filter/RepeaterDataFilter.hpp
ddspipe_participants/include/ddspipe_participants/writer/dds/filter/SelfDataFilter.hpp
ddspipe_participants/include/ddspipe_participants/writer/rtps/CommonWriter.hpp
ddspipe_participants/src/cpp/participant/dds/CommonParticipant.cpp
ddspipe_participants/src/cpp/writer/dds/CommonWriter.cpp
ddspipe_participants/src/cpp/writer/dds/MultiWriter.cpp
ddspipe_participants/src/cpp/writer/dds/QoSSpecificWriter.cpp
ddspipe_participants/src/cpp/writer/dds/SimpleWriter.cpp
ddspipe_participants/src/cpp/writer/dds/filter/RepeaterDataFilter.cpp
ddspipe_participants/src/cpp/writer/dds/filter/SelfDataFilter.cpp
ddspipe_yaml/src/cpp/YamlReader_participants.cpp

This PR adds the possibility to configure DDS (XML) participants so they support the [repeater feature](https://eprosima-dds-router.readthedocs.io/en/latest/rst/use_cases/repeater.html), which up to now has been available only for RTPS participants. The implementation relies on the new feature introduced in https://github.com/eProsima/Fast-DDS/pull/5861.

Support repeater feature in DDS (XML) participants
